# Generated by Django 5.0.6 on 2024-06-07 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_comment_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.ManyToManyField(blank=True, to='client.comment'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='comments',
            field=models.ManyToManyField(blank=True, to='client.comment'),
        ),
    ]
